name: Windows Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Setup
        uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: '14.29'

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.9
        with:
          cmake-version: '3.22.x'

      - name: Build
        run: |
          mkdir build && cd build
          cmake -G"NMake Makefiles" -DCMAKE_BUILD_TYPE=Release ..
          cmake --build .
        shell: cmd
